data:
  name: 'DefaultDataset'
  dir: 'data'
  params:
    idx_fold: 0
    num_fold: 5

model:
  name: 'attention_inceptionv3'
  params:
    attention_size: 8

train:
  dir: './results/attention_inceptionv3'
  batch_size: 16
  num_epochs: 23
  num_grad_acc: 4

eval:
  batch_size: 4

loss:
  name: 'cross_entropy'

optimizer:
  name: 'adam'
  params:
    lr: 0.0005

transform:
  name: 'policy_transform'
  num_preprocessor: 4
  params:
    policies: 'best_policy.data'
    per_image_norm: True
    size: 512
