data:
  name: 'DefaultDataset'
  dir: 'data'
  params:
    idx_fold: 4
    num_fold: 5

model:
  name: 'resnet34'

train:
  dir: './results/resnet34.4.policy'
  batch_size: 32
  num_epochs: 41

loss:
  name: 'binary_focal_loss'

optimizer:
  name: 'adam'
  params:
    lr: 0.0005

transform:
  name: 'policy_transform'
  num_preprocessor: 4
  params:
    policies: 'data/best_policy.data'
